# Generated by Django 5.0.6 on 2024-09-29 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_cabys', models.CharField(max_length=20)),
                ('moneda', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], max_length=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('clasificacion', models.CharField(max_length=50)),
                ('impuesto', models.CharField(choices=[('Exento', 'Exento'), ('Gravado', 'Gravado')], max_length=20)),
                ('inventario_seguimiento', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Salida', 'Salida')], max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='Inventario.producto')),
            ],
        ),
    ]
