# Generated by Django 5.0.6 on 2024-12-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clasificacion',
            field=models.CharField(choices=[('Materiales', 'Materiales'), ('Herramientas', 'Herramientas'), ('Pinturas', 'Pinturas'), ('Solventes', 'Solventes'), ('Maderas', 'Maderas'), ('Aceros', 'Aceros'), ('Plásticos', 'Plásticos'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(choices=[(0, '0%'), (0.05, '5%'), (0.1, '10%'), (0.15, '15%'), (0.2, '20%'), (0.3, '30%'), (0.4, '40%'), (0.5, '50%')], decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares'), ('EUR', 'Euros')], max_length=10),
        ),
    ]
