# Generated by Django 5.0.6 on 2024-12-27 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_producto_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
    ]
