# Generated by Django 5.0.6 on 2025-01-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_inventario_cantidad_alter_inventario_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Metros', 'Metros'), ('Pulgadas', 'Pulgadas'), ('Galones', 'Galones'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
    ]
