# Generated by Django 5.0.6 on 2025-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_cabys',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
