# Generated by Django 5.0.6 on 2024-11-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proforma', '0002_proformadetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProformaDetails',
        ),
    ]
