# Generated by Django 5.0.6 on 2024-12-08 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Proforma", "0003_delete_proformadetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("codigo_cabys", models.CharField(max_length=20)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("CRC", "Colones"), ("USD", "Dólares")], max_length=10
                    ),
                ),
                ("precio_costo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("clasificacion", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="proforma",
            name="descuento",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="detalles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="iva",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="medio_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("transferencia", "Transferencia"),
                    ("cheque", "Cheque"),
                    ("deposito", "Depósito"),
                    ("otros", "Otros"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="nota",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="subtotal",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="total",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="DetalleProforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("descuento", models.FloatField(default=0)),
                ("total", models.FloatField()),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_proformas",
                        to="Proforma.proforma",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Proforma.producto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="proformas",
        ),
    ]
