# Generated by Django 5.0.6 on 2024-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Proforma", "0004_producto_alter_proforma_descuento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleproforma",
            name="producto",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="detalleproforma",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detalleproforma",
            name="precio_unitario",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proforma",
            name="descuento",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="iva",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="medio_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("transferencia", "Transferencia"),
                    ("cheque", "Cheque"),
                    ("deposito", "Deposito"),
                    ("otros", "Otros"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="subtotal",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="total",
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
