# Generated by Django 5.0.6 on 2024-12-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proforma', '0006_alter_detalleproforma_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='regimen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proforma',
            name='situacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proforma',
            name='tipo_identificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
