# Generated by Django 5.0.6 on 2024-12-16 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0003_alter_proveedor_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción del producto')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_orden', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(max_length=300)),
                ('metodo_pago', models.CharField(default='EFECTIVO', max_length=20)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad * Precio unitario', max_digits=15, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedor')),
            ],
        ),
    ]
