# Generated by Django 5.0.6 on 2024-12-11 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden_de_compra', '0001_initial'),
        ('Proveedores', '0002_proveedor_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendecompra',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='ordendecompra',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='IVI',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='lugar_entrega',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedor'),
        ),
    ]
