# Generated by Django 5.0.6 on 2024-11-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden_de_compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
