# Generated by Django 5.0.6 on 2024-10-16 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Orden_de_compra', '0001_initial'),
        ('Proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='id_orden',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedor', verbose_name='Proveedores'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
    ]
