# Generated by Django 5.0.6 on 2024-10-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden_de_compra', '0002_alter_ordendecompra_id_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='id_producto',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='id_proveedor',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='id_usuario',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
