# Generated by Django 5.0.6 on 2024-10-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orden_de_compra', '0002_remove_ordendecompra_id_alter_ordendecompra_id_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='descuento',
        ),
    ]
