# Generated by Django 5.0.6 on 2024-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden_de_compra', '0003_alter_ordendecompra_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad * Precio unitario', max_digits=15, null=True),
        ),
    ]
