# Generated by Django 5.0.6 on 2024-10-17 01:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden_de_compra', '0004_ordendecompra_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='IVI',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
