# Generated by Django 5.0.6 on 2024-12-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
