# Generated by Django 5.0.6 on 2024-11-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0002_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Usuario"), ("admin", "Administrador")],
                default="user",
                max_length=10,
            ),
        ),
    ]
