# Generated by Django 5.0.6 on 2024-12-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CuentaPorCobrar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=255)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_vencimiento", models.DateField()),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("Pendiente", "Pendiente"), ("Pagado", "Pagado")],
                        default="Pendiente",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
