# Generated by Django 5.0.6 on 2024-12-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reportes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura", models.CharField(max_length=20)),
                ("monto_pago", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateField()),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("transferencia", "Transferencia"),
                            ("tarjeta", "Tarjeta"),
                            ("efectivo", "Efectivo"),
                            ("sinpe", "Sinpe"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
