# Generated by Django 5.0.6 on 2024-12-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Proforma", "0006_alter_detalleproforma_proforma"),
        ("Reportes", "0002_pagofactura"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleProforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_unitario", models.FloatField()),
                ("descuento", models.FloatField(default=0.0)),
                ("total", models.FloatField()),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_proformas_reportes",
                        to="Proforma.proforma",
                    ),
                ),
            ],
        ),
    ]
