# Generated by Django 5.0.6 on 2024-12-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajero', models.CharField(max_length=100)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fecha_hora_apertura', models.DateTimeField(auto_now_add=True)),
                ('abierta', models.BooleanField(default=True)),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('codigo_seguridad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.CharField(blank=True, max_length=100, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=100)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('estado_factura', models.CharField(choices=[('Pagada', 'Pagada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=100)),
                ('metodo_pago', models.CharField(default='cash', max_length=100)),
                ('tipo_precio', models.CharField(default='Regular', max_length=100)),
                ('apertura_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='Cajaregistradora.aperturacaja')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('usuario', models.CharField(max_length=100)),
                ('nota', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('codigo_seguridad', models.CharField(blank=True, max_length=50, null=True)),
                ('apertura_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='Cajaregistradora.aperturacaja')),
            ],
        ),
        migrations.CreateModel(
            name='PreCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(blank=True, default='Desconocida', max_length=100, null=True)),
                ('caja_registradora', models.CharField(blank=True, default='Desconocida', max_length=100, null=True)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('cajero', models.CharField(blank=True, default='No disponible', max_length=100, null=True)),
                ('impuestos', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('efectivo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('facturas_proveedor', models.IntegerField(blank=True, default=0, null=True)),
                ('tarjetas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('simpe_movil', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('venta_credito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('movimientos', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('total_ventas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('cantidad_facturas', models.IntegerField(blank=True, default=0, null=True)),
                ('conteo_efectivo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('conteo_tarjetas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('contado_efectivo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('contado_tarjetas', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('codigo_seguridad', models.CharField(blank=True, max_length=50, null=True)),
                ('apertura_caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precierre', to='Cajaregistradora.aperturacaja')),
            ],
        ),
    ]
