# Generated by Django 5.0.6 on 2024-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacaja',
            name='fecha_hora_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
