# Generated by Django 5.0.6 on 2024-12-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='regimen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='situacion_tributaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_identificacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
