# Generated by Django 5.0.6 on 2024-12-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0002_alter_factura_fecha_alter_factura_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_factura',
            field=models.CharField(choices=[('Pagada', 'Pagada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_pago',
            field=models.CharField(default='Efectivo', max_length=20),
        ),
    ]
