# Generated by Django 5.0.6 on 2024-12-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0002_factura_regimen_factura_situacion_tributaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
