# Generated by Django 5.0.6 on 2024-12-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0003_aperturacaja_codigo_seguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientodinero',
            name='codigo_seguridad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
