# Generated by Django 5.0.6 on 2024-12-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0004_registrocaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocaja',
            name='diferencia',
        ),
        migrations.RemoveField(
            model_name='registrocaja',
            name='hora_cierre',
        ),
        migrations.RemoveField(
            model_name='registrocaja',
            name='total_calculado',
        ),
        migrations.RemoveField(
            model_name='registrocaja',
            name='total_real',
        ),
        migrations.AddField(
            model_name='registrocaja',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10),
        ),
        migrations.AlterField(
            model_name='registrocaja',
            name='hora_apertura',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
