# Generated by Django 5.0.6 on 2024-12-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0005_remove_registrocaja_diferencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroCaja',
        ),
    ]
