# Generated by Django 5.0.6 on 2024-12-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0006_delete_registrocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajero', models.CharField(max_length=100)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora_apertura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
