# Generated by Django 5.0.6 on 2024-12-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0007_aperturacaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
                ('nota', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_seguridad', models.CharField(max_length=20)),
            ],
        ),
    ]
