# Generated by Django 5.0.6 on 2024-12-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0008_movimientodinero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientodinero',
            name='codigo_seguridad',
        ),
    ]
