# Generated by Django 5.0.6 on 2024-12-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0009_remove_movimientodinero_codigo_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodinero',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
