# Generated by Django 5.0.6 on 2024-12-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0010_alter_movimientodinero_fecha_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=100)),
                ('caja_registradora', models.CharField(max_length=100)),
                ('hora_apertura', models.TimeField()),
                ('fecha', models.DateField()),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cajero', models.CharField(max_length=100)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facturas_proveedor', models.IntegerField()),
                ('tarjetas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('simpe_movil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movimientos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_facturas', models.IntegerField()),
                ('conteo_efectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conteo_tarjetas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contado_efectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contado_tarjetas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
