# Generated by Django 5.0.6 on 2024-12-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0011_precierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precierre',
            name='cantidad_facturas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='contado_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='contado_tarjetas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='conteo_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='conteo_tarjetas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='facturas_proveedor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='movimientos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='simpe_movil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='tarjetas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='venta_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
