# Generated by Django 5.0.6 on 2024-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cajaregistradora', '0012_alter_precierre_cantidad_facturas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precierre',
            name='caja_registradora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='cajero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='cantidad_facturas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='contado_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='contado_tarjetas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='conteo_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='conteo_tarjetas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='facturas_proveedor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='impuestos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='monto_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='movimientos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='simpe_movil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='tarjetas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='total_ventas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='precierre',
            name='venta_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
