# Generated by Django 5.0.6 on 2024-12-10 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_ruta_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaPrecio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_ruta', models.DecimalField(choices=[(5000, '5000'), (10000, '10000')], decimal_places=2, max_digits=10)),
                ('kilometro', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportes.ruta')),
            ],
        ),
    ]
