# Generated by Django 5.0.6 on 2024-12-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0003_rutaprecio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='id',
        ),
        migrations.AlterField(
            model_name='conductor',
            name='id_conductor',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
