# Generated by Django 5.0.6 on 2025-03-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0009_auto_20250322_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='nombre_conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportes.conductor'),
        ),
    ]
