# Generated by Django 5.0.6 on 2024-11-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_activo_alter_cliente_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
