# Generated by Django 5.0.6 on 2024-10-06 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='DEFAULT_VALUE', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombreempresa', models.CharField(max_length=100)),
                ('tipoIdentificacion', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('canton', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono1', models.CharField(max_length=100)),
                ('telefono2', models.CharField(max_length=100)),
            ],
        ),
    ]
