# Generated by Django 5.0.6 on 2024-10-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_exacta',
            field=models.TextField(default='direccion', max_length=255),
        ),
    ]
